### ISSUE TITLE
Missing Images in a Lap Around Spark Tutorial

### ISSUE THREAD

**Issue by roberthryniewicz** [ZacBlanco/hwx-tutorials#74]
What happened to the images?
https://github.com/ZacBlanco/hwx-tutorials/blob/hdp/tutorials/hortonworks/a-lap-around-spark/tutorial.md

**Comment by roberthryniewicz** [comment]
Closing per Zac's update that hwx-tutorials should no longer be used.

**Comment by james94** [comment]
The Image was missing because the forward slash `/` between "assets" and "a-lap-around-spark" was missing in the file path below: 

(/assetsa-lap-around-spark/Screenshot%202015-07-21%2013.53.04.png?dl=1)

Once the forward slash is added into the path, the image error resolves.

(/assets`/`a-lap-around-spark/Screenshot%202015-07-21%2013.53.04.png?dl=1)
